[package]
name = "infinitinote_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.183"
web-sys = { version = "0.3.60" }
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
sha256 = "=1.1.5"
derive_more = "0.99.17"
<<<<<<< HEAD
compiler_builtins = "0.1.93"
=======
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde_tokenstream = "0.2.0"
candid = "0.9.3"
>>>>>>> origin/master
